if(NOT DEFINED POSE_PROJECT OR NOT DEFINED CASE)
  message(FATAL_ERROR "POSE_PROJECT and CASE are required")
endif()

if(CASE STREQUAL "invalid-mode")
  set(args --mode invalid)
  set(expected "--mode must be lookat, gt or both")
elseif(CASE STREQUAL "missing-input")
  set(args --data "${CMAKE_BINARY_DIR}/missing-task-7-input" --mode lookat)
  set(expected "error:")
elseif(CASE STREQUAL "both")
  set(output_dir "${POSE_OUTPUT}")
  file(REMOVE_RECURSE "${output_dir}")
  set(args --data "${POSE_DATA}" --out "${output_dir}" --mode both)
else()
  message(FATAL_ERROR "unknown CLI test case: ${CASE}")
endif()

execute_process(
  COMMAND "${POSE_PROJECT}" ${args}
  RESULT_VARIABLE result
  OUTPUT_VARIABLE stdout
  ERROR_VARIABLE stderr)
set(output "${stdout}${stderr}")

if(CASE STREQUAL "both")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "expected pose-project --mode both to succeed, but it exited with ${result}:\n${output}")
  endif()
  if(NOT output MATCHES "wrote 20 white renders")
    message(FATAL_ERROR "expected successful batch output, got:\n${output}")
  endif()

  function(assert_csv path expected_lines expected_header row_pattern)
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "expected artifact does not exist: ${path}")
    endif()
    file(STRINGS "${path}" lines)
    list(LENGTH lines line_count)
    if(NOT line_count EQUAL ${expected_lines})
      message(FATAL_ERROR "expected ${path} to have ${expected_lines} lines, got ${line_count}")
    endif()
    list(GET lines 0 header)
    if(NOT header STREQUAL "${expected_header}")
      message(FATAL_ERROR "unexpected header in ${path}: '${header}'")
    endif()
    list(REMOVE_AT lines 0)
    foreach(line IN LISTS lines)
      if(NOT line MATCHES "${row_pattern}")
        message(FATAL_ERROR "unexpected row shape in ${path}: '${line}'")
      endif()
    endforeach()
  endfunction()

  set(coordinate_row "^[0-9]+,[^,]+,[0-9]+,[^,]+,-?[0-9]+\\.[0-9][0-9],-?[0-9]+\\.[0-9][0-9],-?[0-9]+\\.[0-9][0-9],-?[0-9]+\\.[0-9][0-9]$")
  assert_csv("${output_dir}/coords/all-2d-coordinates.csv" 281
             "frame,camera,joint,name,u_lookat,v_lookat,u_gt,v_gt" "${coordinate_row}")
  set(error_row "^[0-9]+,[^,]+,-?[0-9]+\\.[0-9][0-9],-?[0-9]+\\.[0-9][0-9],[0-9]+,-?[0-9]+\\.[0-9][0-9][0-9][0-9]$")
  assert_csv("${output_dir}/analysis/joint-error.csv" 21
             "frame,camera,mean_px,max_px,worst_joint,angular_deg" "${error_row}")
  set(angular_row "^[0-9]+,[^,]+,-?[0-9]+\\.[0-9][0-9][0-9][0-9]$")
  assert_csv("${output_dir}/analysis/camera-angular-error.csv" 21
             "frame,camera,angular_deg" "${angular_row}")
  set(status_row "^[0-9]+,[^,]+,(valid|behind-camera|unmatched-camera),[0-9]+,(valid|behind-camera|unmatched-camera),[0-9]+$")
  assert_csv("${output_dir}/analysis/projection-status.csv" 21
             "frame,camera,lookat_status,lookat_invalid_joints,gt_status,gt_invalid_joints"
             "${status_row}")

  set(coordinate_tex "${output_dir}/coords/all-2d-coordinates.tex")
  if(NOT EXISTS "${coordinate_tex}")
    message(FATAL_ERROR "expected artifact does not exist: ${coordinate_tex}")
  endif()
  file(READ "${coordinate_tex}" tex_contents)
  string(REGEX MATCHALL "\n" tex_newlines "${tex_contents}")
  list(LENGTH tex_newlines tex_line_count)
  if(NOT tex_line_count EQUAL 287)
    message(FATAL_ERROR "expected ${coordinate_tex} to have 287 lines, got ${tex_line_count}")
  endif()
  string(FIND "${tex_contents}" [=[\begin{longtable}{rlrlrrrr}]=] tex_opening)
  if(tex_opening LESS 0)
    message(FATAL_ERROR "missing TeX table opening in ${coordinate_tex}")
  endif()
  string(FIND "${tex_contents}" [=[Frame & Camera & \# & Joint & $u_{\text{look-at}}$ & $v_{\text{look-at}}$ & $u_{\text{gt}}$ & $v_{\text{gt}}$ \\]=] tex_header)
  if(tex_header LESS 0)
    message(FATAL_ERROR "missing TeX table header in ${coordinate_tex}")
  endif()
else()
  if(result EQUAL 0)
    message(FATAL_ERROR "expected pose-project to fail, but it exited successfully")
  endif()
  if(NOT output MATCHES "${expected}")
    message(FATAL_ERROR "expected '${expected}' in CLI output, got:\n${output}")
  endif()
  message("observed expected CLI failure: ${output}")
endif()
