if(NOT DEFINED POSE_PROJECT OR NOT DEFINED CASE)
  message(FATAL_ERROR "POSE_PROJECT and CASE are required")
endif()

if(CASE STREQUAL "invalid-mode")
  set(args --mode invalid)
  set(expected "--mode must be lookat, gt or both")
elseif(CASE STREQUAL "missing-input")
  set(args --data "${CMAKE_BINARY_DIR}/missing-task-7-input" --mode lookat)
  set(expected "error:")
elseif(CASE STREQUAL "both")
  set(output_dir "${POSE_OUTPUT}")
  file(REMOVE_RECURSE "${output_dir}")
  set(args --data "${POSE_DATA}" --out "${output_dir}" --mode both)
else()
  message(FATAL_ERROR "unknown CLI test case: ${CASE}")
endif()

execute_process(
  COMMAND "${POSE_PROJECT}" ${args}
  RESULT_VARIABLE result
  OUTPUT_VARIABLE stdout
  ERROR_VARIABLE stderr)
set(output "${stdout}${stderr}")

if(CASE STREQUAL "both")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "expected pose-project --mode both to succeed, but it exited with ${result}:\n${output}")
  endif()
  if(NOT output MATCHES "wrote 20 white renders")
    message(FATAL_ERROR "expected successful batch output, got:\n${output}")
  endif()
else()
  if(result EQUAL 0)
    message(FATAL_ERROR "expected pose-project to fail, but it exited successfully")
  endif()
  if(NOT output MATCHES "${expected}")
    message(FATAL_ERROR "expected '${expected}' in CLI output, got:\n${output}")
  endif()
  message("observed expected CLI failure: ${output}")
endif()
